### PR TITLE
Add option to substitute on the target machine if local build

### PR DESCRIPTION
**Pull request by MagicRB**
Signed-off-by: Magic_RB <magic_rb@redalder.org>

### CODE REVIEW

**Comment by MagicRB** [comment]
Draft :)

**Comment by Kranzes** [comment]
Isn't using substitutors on the target machine inherently better, shouldn't that just be the default/always enabled?

**Comment by MagicRB** [comment]
thats up to mathew to decide

**Comment by MatthewCroughan** [comment]
I've decided not to enable it by default, since it's too risky that the remote will have a low upload bandwidth. Part of the reason someone would want to build locally is because they don't want to be hampered by the remote, so it's best to leave this up to the user rather than decide for them.

**Comment by MatthewCroughan** [comment]
This passed CI https://hercules-ci.com/github/MatthewCroughan/nixinate/jobs/37

**Pull request merged**
