### PR TITLE
Add dry runs.

### PR DESCRIPTION
**Pull request by pinktrink**

### CODE REVIEW

**Review by MatthewCroughan — APPROVED** [review]
This is perfect. Thank you for splitting up the commits, I totally understand the thought process now.

**Review by nixinator — APPROVED** [review]
the nixinator approves of this revision of nixinate. nice work @pinktrink

**Comment by pinktrink** [comment]
Thanks!

**Comment by nixinator** [comment]
you may qualify for nixinate swag.

**Comment by MatthewCroughan** [comment]
I've tested that this doesn't break existing usage. I will set up a NixOS test and CI shortly.

**Pull request merged**
