### PR TITLE
Use explicit cross-platform flock rather than impurely referencing it

### PR DESCRIPTION
**Pull request by MatthewCroughan**
This solves #29

### CODE REVIEW

**Comment by Kranzes** [comment]
Could also use flock from util-linux

**Comment by MatthewCroughan** [comment]
@Kranzes Best to avoid locking ourselves into Linux. Right now, technically all of our utilities are not linux specific.

**Comment by Kranzes** [comment]
Does nixos-rebuild work on darwin?

**Comment by MatthewCroughan** [comment]
@Kranzes No, but I was thinking of having multiple backends, which would solve that problem. So the deployment can be implemented by any backend.

**Comment by Gerschtli** [comment]
I am having trouble with this change because the locally references nix store path of flock is not available on my target machine, resulting in

```
sudo: /nix/store/wrdk8aqwq7h0lyjglkqgf4x7izd2ymsc-flock-0.2.3/bin/flock: command not found
```

But I would not be able to call `nix store --realise /nix/store/wrdk8aqwq7h0lyjglkqgf4x7izd2ymsc-flock-0.2.3/bin/flock` after `nix copy` with a file lock using `flock`, some chicken-egg problem here..

Should I create a separate issue for it?

**Comment by MatthewCroughan** [comment]
@Gerschtli That's interesting, and it should have been caught by my VM Tests, this indicates my VM Tests are not good enough.

**Pull request merged**
